local ura = require("ura")
ura.env("WLR_RENDERER", "vulkan")
ura.env("LIBVA_DRIVER_NAME", "nvidia");
ura.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
ura.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
ura.env("XCURSOR_SIZE", "24")
ura.env("GDK_DPI_SCALE", "1")
ura.env("GDK_SCALE", "1")
ura.env("XCURSOR_SIZE", "32")
ura.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
ura.env("QT_ENABLE_HIGHDPI_SCALING", "0")
ura.env("QT_SCALE_FACTOR", "1")
ura.env("QT_STYLE_OVERRIDE", "kvantum")
