#!/bin/bash

case "$1" in
"close")
  ura-shell -c "ura.cmd.close()"
  ;;
"focus-prev")
  ura-shell -c "ura.cmd.focus_prev()"
  ;;
"focus-next")
  ura-shell -c "ura.cmd.focus_next()"
  ;;
"swap-prev")
  ura-shell -c "ura.cmd.swap_prev()"
  ;;
"swap-next")
  ura-shell -c "ura.cmd.swap_next()"
  ;;
"switch-prev")
  ura-shell -c "ura.cmd.switch_prev()"
  ;;
"switch-next")
  ura-shell -c "ura.cmd.switch_next()"
  ;;
"move-to-prev")
  ura-shell -c "ura.cmd.move_to_prev()"
  ;;
"move-to-next")
  ura-shell -c "ura.cmd.move_to_next()"
  ;;
"toggle-layout")
  [[ -n "$2" ]] &&
    ura-shell -c "ura.cmd.toggle_layout([[$2]])"
  ;;
"list-commands")
  echo "$PATH" | tr ':' '\n' |
    xargs -I 'PATH' find PATH -name 'ura-*' 2>/dev/null |
    xargs -n1 basename |
    sed 's/ura-//' | sort | uniq
  ;;
"focus-follow-mouse")
  if [[ -n "$2" ]]; then
    case "$2" in
    "false" | "0") ura shell -c "ura.opt.focus_follow_mouse=false" ;;
    "true" | "1") ura shell -c "ura.opt.focus_follow_mouse=true" ;;
    *)
      echo invalid arguments: "$2", expects: "false|true|0|1"
      exit 1
      ;;
    esac
  else
    ura shell -c "print(ura.opt.focus_follow_mouse)"
  fi
  ;;
"set-pointer-accel-profile")
  if [[ -n "$2" ]]; then
    if [[ -n "$3" ]]; then
      ura shell -c "ura.api.set_pointer_accel_profile(\"$2\", \"$3\")"
    else
      echo 'invalid arguments, expects: set-pointer-accel-profile <profile> <glob>'
      exit 1
    fi
  else
    echo 'invalid arguments, expects: set-pointer-accel-profile <profile> <glob>'
    exit 1
  fi
  ;;
*)
  echo "Command not found: $1"
  exit 1
  ;;
esac
