#!/usr/bin/bash

case "$1" in
"hook")
  ura-shell -c "print(ura.api.to_json(ura.hook.HOOKS))" | jq
  ;;
"layout")
  ura-shell -c "print(ura.api.to_json(ura.layout.LAYOUTS))" | jq
  ;;
"windows")
  ura-shell -c '
local t = {}
for _, w in ipairs(ura.class.UraWindow:all()) do
  t[tostring(w.id)] = {
		app_id = w:app_id(),
		title = w:title(),
		output = w:output():name(),
		geometry = w:geometry(),
		z_index = w:z_index(),
		is_draggable = w:is_draggable(),
		is_fullscreen = w:is_fullscreen(),
		userdata = w:userdata(),
		tags = w:tags(),
	}
end
print(ura.api.to_json(t))
  ' | jq
  ;;
"-h" | "--help" | *)
  echo Usage:
  echo 'ura-debug [Commands]'
  echo 'ura-debug [Options]'
  echo
  echo Commands:
  echo hook
  echo layout
  echo windows
  echo
  echo Options:
  echo -h, --help Print this help message and exit
  ;;
esac
